package com.mateuszholik.designsystem.theme

import androidx.compose.ui.graphics.Color

internal val md_theme_light_primary = Color(0xFF000000)
internal val md_theme_light_onPrimary = Color(0xFFFFFFFF)
internal val md_theme_light_primaryContainer = Color(0xFFF2F2F7)
internal val md_theme_light_onPrimaryContainer = Color(0xFF1C1C1E)
internal val md_theme_light_secondary = Color(0xFF636366)
internal val md_theme_light_onSecondary = Color(0xFFFFFFFF)
internal val md_theme_light_secondaryContainer = Color(0xFFE5E5EA)
internal val md_theme_light_onSecondaryContainer = Color(0xFF3A3A3C)
internal val md_theme_light_tertiary = Color(0xFF007AFF) // Subtle Blue Accent
internal val md_theme_light_onTertiary = Color(0xFFFFFFFF)
internal val md_theme_light_tertiaryContainer = Color(0xFFD1E9FF)
internal val md_theme_light_onTertiaryContainer = Color(0xFF004080)
internal val md_theme_light_error = Color(0xFFFF3B30)
internal val md_theme_light_errorContainer = Color(0xFFFFD6D4)
internal val md_theme_light_onError = Color(0xFFFFFFFF)
internal val md_theme_light_onErrorContainer = Color(0xFF8E0000)
internal val md_theme_light_background = Color(0xFFF9F9F9) // Off-white for softness
internal val md_theme_light_onBackground = Color(0xFF1C1C1E)
internal val md_theme_light_surface = Color(0xFFFFFFFF)
internal val md_theme_light_onSurface = Color(0xFF1C1C1E)
internal val md_theme_light_surfaceVariant = Color(0xFFE5E5EA)
internal val md_theme_light_onSurfaceVariant = Color(0xFF3A3A3C)
internal val md_theme_light_outline = Color(0xFFC7C7CC)
internal val md_theme_light_inverseOnSurface = Color(0xFFF2F2F7)
internal val md_theme_light_inverseSurface = Color(0xFF1C1C1E)
internal val md_theme_light_inversePrimary = Color(0xFFFFFFFF)
internal val md_theme_light_shadow = Color(0x1A000000)
internal val md_theme_light_surfaceTint = Color(0xFF000000)
internal val md_theme_light_outlineVariant = Color(0xFFD1D1D6)
internal val md_theme_light_scrim = Color(0xFF000000)

internal val md_theme_dark_primary = Color(0xFFFFFFFF)
internal val md_theme_dark_onPrimary = Color(0xFF000000)
internal val md_theme_dark_primaryContainer = Color(0xFF1C1C1E)
internal val md_theme_dark_onPrimaryContainer = Color(0xFFF2F2F7)
internal val md_theme_dark_secondary = Color(0xFFAEAEB2)
internal val md_theme_dark_onSecondary = Color(0xFF000000)
internal val md_theme_dark_secondaryContainer = Color(0xFF2C2C2E)
internal val md_theme_dark_onSecondaryContainer = Color(0xFFE5E5EA)
internal val md_theme_dark_tertiary = Color(0xFF0A84FF)
internal val md_theme_dark_onTertiary = Color(0xFFFFFFFF)
internal val md_theme_dark_tertiaryContainer = Color(0xFF003366)
internal val md_theme_dark_onTertiaryContainer = Color(0xFFD1E9FF)
internal val md_theme_dark_error = Color(0xFFFF453A)
internal val md_theme_dark_errorContainer = Color(0xFF410002)
internal val md_theme_dark_onError = Color(0xFFFFFFFF)
internal val md_theme_dark_onErrorContainer = Color(0xFFFFD6D4)
internal val md_theme_dark_background = Color(0xFF000000)
internal val md_theme_dark_onBackground = Color(0xFFF2F2F7)
internal val md_theme_dark_surface = Color(0xFF1C1C1E)
internal val md_theme_dark_onSurface = Color(0xFFF2F2F7)
internal val md_theme_dark_surfaceVariant = Color(0xFF2C2C2E)
internal val md_theme_dark_onSurfaceVariant = Color(0xFFAEAEB2)
internal val md_theme_dark_outline = Color(0xFF636366)
internal val md_theme_dark_inverseOnSurface = Color(0xFF000000)
internal val md_theme_dark_inverseSurface = Color(0xFFF2F2F7)
internal val md_theme_dark_inversePrimary = Color(0xFF000000)
internal val md_theme_dark_shadow = Color(0xFF000000)
internal val md_theme_dark_surfaceTint = Color(0xFFFFFFFF)
internal val md_theme_dark_outlineVariant = Color(0xFF3A3A3C)
internal val md_theme_dark_scrim = Color(0xFF000000)


internal val seed = Color(0xFF000000)
